[package]
name = "eloran"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6", features = ["macros"] }
# axum = "0.6"
horrorshow = "0.8.4"
http = "0.2.8"
body = "0.1.1"
env_logger = "0.10.0"
log = "0.4.17"
# need tower for redirect when not logged in
tower = "0.4.13"
ulid = "1.0.0"
jwalk = "0.8.1"
image = "0.24.5"
epub = "2.0.0"
# TODO remove b64
base64 = "0.21.0"
compress-tools = "0.14.0"
libc = "0.2.140"
# clap = { version = "4.1.13", default-features = false, features = ["std"] }
clap = "4.1.13"
config = "0.13.3"
poppler-rs = "0.21.0"
cairo-rs = { version = "0.17.0", features = ["png", "pdf"] }
urlencoding = "2.1.2"
# async-sqlx-session = { version = "0.4.0", features = ["sqlite"] }
[dependencies.axum-login]
version = "0.4"
features = ["sqlite"]
[dependencies.rand]
version = "0.8"
features = ["min_const_gen"]
[dependencies.sqlx]
version = "0.6"
default-features = false
features = ["runtime-tokio-rustls", "sqlite"]
[dependencies.tokio]
version = "1.24"
features = ["full"]

[dev-dependencies]
axum-test-helper = { version = "0.*" }

[profile.release]
panic = 'abort' # No unwinding on panic
strip = true  # Automatically strip symbols from the binary.
opt-level = "s"  # Optimize for size.
lto = true
codegen-units = 1
